version: "3.5"

services:
  proxy:
    image: nginx
    container_name: "proxy"
    restart: unless-stopped
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - author-reports:/var/www/html:ro
      - ./.env:/var/www/html/.env:ro
    depends_on:
      - author-reports

  author-reports:
    image: openbookpublishers/author-reports
    container_name: "author_reports"
    restart: unless-stopped
    volumes:
      - ./.env:/var/www/html/.env:ro
      - author-reports:/var/www/html

volumes:
  author-reports:
